### ISSUE TITLE
dependencies issue

### ISSUE THREAD

**Issue by bftjoe** [oakmac/chessboard2#39]
The correct command for yarn is yarnpkg, not yarn, at least if using yarn installed from Ubuntu 22.10 package manager.

Do you mean no runtime dependencies? Probably should specify that, I see plenty of development dependencies.

Thanks for your work on pickupultimate.com, btw.

**Comment by oakmac** [comment]
> The correct command for yarn is yarnpkg, not yarn, at least if using yarn installed from Ubuntu 22.10 package manager.

I expect this will vary from system to system. I think `yarn` is probably the most popular convention.

> Do you mean no runtime dependencies? Probably should specify that, I see plenty of development dependencies.

Yes - "no dependencies" means no runtime dependencies for the library as it is shipped. This is in contrast to [chessboard.js](https://github.com/oakmac/chessboardjs) which requires jQuery.

> Thanks for your work on pickupultimate.com, btw.

Thank you! 🙏
