### ISSUE TITLE
question about analysis arrows

### ISSUE THREAD

**Issue by oakmac** [oakmac/chessboard2#40]
I received this email with questions about chessboard2. I wanted to reply publicly for the benefit of others who might have similar questions.

<hr>

Hi Chris,

I’m looking into using chessboard2 in an app I’m working on and analysis arrows are really important for its functionality.

When I browsed through the docs I did not see them documented and even the references to their methods from https://chessboardjs.com/v2/examples#3008-analysis-arrows did not lead anywhere.

A few questions if I may:
 1. How stable is the current version?
 2. Any idea when a release version will be available?
 3. How are the arrows and circles stored internally as i would like to save them along with the game?
 4. Any recommended approach to drawing them using the mouse rather than programatically? onDrag…() seem to work on pieces so I assume I need to handle the mouse events separately from chessbord’s APIs. 

I hope you provide some insight on the above.

Thank you so much,

**Comment by djeetee** [comment]
on the last point, either a .onClickSquare() or a mouse coordinates (from the click event)-to-square method would be also good.

**Comment by oakmac** [comment]
@djeetee the master branch now has two examples of dynamically adding arrows to the board using mouse events ([PR #41](https://github.com/oakmac/chessboard2/pull/41))

**Comment by oakmac** [comment]
This is supported by [v0.4.0](https://www.npmjs.com/package/@chrisoakman/chessboard2)

- https://chessboardjs.com/v2/examples#4015-mouse-enter-leave-squares
- https://chessboardjs.com/v2/examples#4016-mouse-down-up-squares
- https://chessboardjs.com/v2/examples#5006-click-to-create-arrows
- https://chessboardjs.com/v2/examples#5007-click-to-create-arrows-preview

**Comment by djeetee** [comment]
Hey Chris, I hope all is well.

I finally sunk my teeth into chessboard2. I have the board set up, i can feed positions, moves, navigate, etc… So far so good.

My question/comment is this: it would be great if one could enable/disable play for one of the two players. In other words, being able to stop one color from moving their pieces.

Say I’m playing white and waiting for black to move, I shouldn’t be able to move my own piece (unless of course I want to enable pre-moves which another use-case on its own) but at least I’m not changing the state of the board during the other player’s turn.

Is there a clean way to do that with the current functionality or do I have to code the logic?

Thank you,


-George

**Comment by oakmac** [comment]
> it would be great if one could enable/disable play for one of the two players. In other words, being able to stop one color from moving their pieces.

I think [Example 4002](https://chessboardjs.com/v2/examples#4002-ondragstart-prevent-drag) demonstrates the behavior you want.
