### ISSUE TITLE
How can I customize the Chessboard2 UI?

### ISSUE THREAD

**Issue by hiayushh** [oakmac/chessboard2#46]
I'd like to use Chessboard 2 for a business application. But we'd like to have the option of changing the board colors, putting custom chess pieces etc. 

Is this currently possible in the project? If yes, how?
Otherwise, is this something you have in plan @oakmac?

**Comment by oakmac** [comment]
> But we'd like to have the option of changing the board colors

I intend to support changing the background color of squares via CSS (ie: not via the JS API). This is possible now by targeting the [snowflaked class names](https://github.com/oakmac/snowflake-css) in [chessboard2.css](https://github.com/oakmac/chessboard2/blob/master/src-css/chessboard2.css). I may add additional classes to that file before v2.0.0, but I have no plans to change the definitions of classes that exist now.

> putting custom chess pieces

I intend to support custom board items in chessboard2. There is some support for this already (see [Example 9002](https://chessboardjs.com/v2/examples/9002)), but this API may change before v2.0.0.
